export const LANGUAGES = {
    "Spanish": "spa_Latn",
    "French": "fra_Latn",
    "German": "deu_Latn",
    "Portuguese": "por_Latn",
    "Modern Standard Arabic": "arb",
    "Simplified Chinese": "zho_Hans",
    "Traditional Chinese": "zho_Hant",
    "Russian": "rus_Cyrl",
    "Hindi": "hin_Deva",
    "Japanese": "jpn_Jpan",
    "Italian": "ita_Latn",
    "Finnish": "fin_Latn",
    "Czech": "Czech",
    "Danish": "dan_Latn",
    "Greek": "ell_Grek",
    "Polish": "pol_Latn",
    "Swedish": "swe_Latn",
    "Norwegian": "nno_Latn",
    "Korean": "kor_Hang",
  }